RegisterCommand("try", function()
    SendNUIMessage({ban = "Salut"})
end, false)

RegisterCommand("ani", function()
    Camera = CreateCam('DEFAULT_SCRIPTED_CAMERA', true)
    SetCamCoord(Camera,0,0,1500.0)
    SetCamRot(Camera, -90.0, 0.0, 0.0, true)
    SetCamFov(Camera,100.0)
    ShakeCam(Camera,"HAND_SHAKE",0.9)
    SetCamActive(Camera, true)
    PlaySoundFrontend(-1, "Short_Transition_In", "PLAYER_SWITCH_CUSTOM_SOUNDSET")
    RenderScriptCams(true, true, 10, true, true)
    SetTimecycleModifier("DefaultColorCode")
end, false)